# Generated by Django 5.1.6 on 2025-02-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogpost_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.ManyToManyField(to="blog.category"),
        ),
    ]
